// packages/vue/src/components/DateRenderer.vue
<script setup lang="ts">
import type { FormField } from 'pdyform-core';
import Input from './Input.vue';

defineProps<{
  field: FormField;
  modelValue: string;
  fieldId: string;
  ariaInvalid?: boolean;
  ariaRequired?: boolean;
  ariaDescribedby?: string;
}>();

const emit = defineEmits(['update:modelValue', 'blur']);
</script>

<template>
  <Input
    :id="fieldId"
    type="date"
    :model-value="modelValue"
    :placeholder="field.placeholder"
    :disabled="typeof field.disabled === 'boolean' ? field.disabled : undefined"
    :name="field.name"
    :aria-invalid="ariaInvalid"
    :aria-required="ariaRequired"
    :aria-describedby="ariaDescribedby"
    @update:model-value="emit('update:modelValue', $event)"
    @blur="emit('blur', $event)"
  />
</template>

// packages/react/src/components/DateRenderer.tsx
import React from 'react';
import type { FieldRenderContext } from './types';
import { Input } from './Input';

const DateRenderer: React.FC<FieldRenderContext> = ({
  field,
  value,
  onChange,
  onBlur,
  fieldId,
  ariaInvalid,
  ariaRequired,
  ariaDescribedBy,
}) => {
  return (
    <Input
      id={fieldId}
      type="date"
      value={value ?? ''}
      onChange={(e) => onChange(e.target.value)}
      onBlur={onBlur}
      disabled={typeof field.disabled === 'boolean' ? field.disabled : undefined}
      name={field.name}
      aria-invalid={ariaInvalid}
      aria-required={ariaRequired}
      aria-describedby={ariaDescribedBy}
    />
  );
};

export default DateRenderer;
