// packages/vue/src/components/InputRenderer.vue
<script setup lang="ts">
import type { FieldRendererProps } from '../fieldComponentMap';
import Input from '../components/Input.vue';

const props = defineProps<FieldRendererProps>();
const emit = defineEmits<{ 'update:modelValue': [value: any] }>();
</script>

<template>
  <Input
    :id="fieldId"
    :type="field.type"
    :placeholder="field.placeholder"
    :disabled="field.disabled"
    :name="field.name"
    :modelValue="modelValue ?? ''"
    @update:modelValue="emit('update:modelValue', $event)"
  />
</template>

// packages/react/src/components/InputRenderer.tsx
import React from 'react';
import type { FieldRenderContext } from './types';
import { Input } from './Input';

const InputRenderer: React.FC<FieldRenderContext> = ({ field, value, onChange, onBlur, fieldId }) => (
  <Input
    id={fieldId}
    type={field.type}
    placeholder={field.placeholder}
    value={value ?? ''}
    onChange={(e) => onChange(e.target.value)}
    onBlur={onBlur}
    disabled={field.disabled}
    name={field.name}
  />
);

export default InputRenderer;
