// packages/vue/src/components/RadioRenderer.vue
<script setup lang="ts">
import type { FieldRendererProps } from '../fieldComponentMap';
import RadioGroup from '../components/RadioGroup.vue';
import RadioGroupItem from '../components/RadioGroupItem.vue';
import Label from '../components/Label.vue';

const props = defineProps<FieldRendererProps>();
const emit = defineEmits<{ 'update:modelValue': [value: any] }>();
</script>

<template>
  <RadioGroup
    class="flex flex-wrap gap-4"
    :disabled="typeof field.disabled === 'boolean' ? field.disabled : undefined"
    :name="field.name"
    :modelValue="modelValue != null ? String(modelValue) : ''"
    @update:modelValue="emit('update:modelValue', $event)"
  >
    <div v-for="opt in field.options" :key="opt.value" class="flex items-center space-x-2">
      <RadioGroupItem :id="`radio-${field.name}-${opt.value}`" :value="String(opt.value)" />
      <Label :for="`radio-${field.name}-${opt.value}`" class="font-normal">{{ opt.label }}</Label>
    </div>
  </RadioGroup>
</template>

// packages/react/src/components/RadioRenderer.tsx
import React from 'react';
import type { FieldRenderContext } from './types';
import { RadioGroup, RadioGroupItem } from './RadioGroup';
import { Label } from './Label';

const RadioRenderer: React.FC<FieldRenderContext> = ({ field, value, onChange, onBlur }) => (
  <RadioGroup
    value={value != null ? String(value) : ''}
    onValueChange={onChange}
    disabled={typeof field.disabled === 'boolean' ? field.disabled : undefined}
    name={field.name}
    className="flex flex-wrap gap-4"
  >
    {field.options?.map((opt) => (
      <div key={opt.value} className="flex items-center space-x-2">
        <RadioGroupItem
          value={String(opt.value)}
          id={`radio-${field.name}-${opt.value}`}
          onBlur={onBlur}
        />
        <Label htmlFor={`radio-${field.name}-${opt.value}`} className="font-normal">
          {opt.label}
        </Label>
      </div>
    ))}
  </RadioGroup>
);

export default RadioRenderer;
