// packages/vue/src/components/TextareaRenderer.vue
<script setup lang="ts">
import type { FieldRendererProps } from '../fieldComponentMap';
import Textarea from '../components/Textarea.vue';

const props = defineProps<FieldRendererProps>();
const emit = defineEmits<{ 'update:modelValue': [value: any] }>();
</script>

<template>
  <Textarea
    :id="fieldId"
    :placeholder="field.placeholder"
    :disabled="typeof field.disabled === 'boolean' ? field.disabled : undefined"
    :name="field.name"
    :modelValue="modelValue ?? ''"
    @update:modelValue="emit('update:modelValue', $event)"
  />
</template>

// packages/react/src/components/TextareaRenderer.tsx
import React from 'react';
import type { FieldRenderContext } from './types';
import { Textarea } from './Textarea';

const TextareaRenderer: React.FC<FieldRenderContext> = ({ field, value, onChange, onBlur, fieldId }) => (
  <Textarea
    id={fieldId}
    placeholder={field.placeholder}
    value={value ?? ''}
    onChange={(e) => onChange(e.target.value)}
    onBlur={onBlur}
    disabled={typeof field.disabled === 'boolean' ? field.disabled : undefined}
    name={field.name}
  />
);

export default TextareaRenderer;
