// packages/react/src/components/CheckboxRenderer.tsx
import React from 'react';
import type { FieldRenderContext } from './types';
import { Checkbox } from './Checkbox';
import { Label } from './Label';

const CheckboxRenderer: React.FC<FieldRenderContext> = ({ field, value, onChange, onBlur }) => (
  <div className="flex flex-wrap gap-4">
    {field.options?.map((opt) => {
      const checked = Array.isArray(value) && value.includes(opt.value);
      return (
        <div key={opt.value} className="flex items-center space-x-2">
          <Checkbox
            id={`checkbox-${field.name}-${opt.value}`}
            checked={checked}
            disabled={typeof field.disabled === 'boolean' ? field.disabled : undefined}
            onCheckedChange={(c) => {
              const next = Array.isArray(value) ? [...value] : [];
              if (c) {
                next.push(opt.value);
              } else {
                const idx = next.indexOf(opt.value);
                if (idx > -1) next.splice(idx, 1);
              }
              onChange(next);
            }}
            onBlur={onBlur}
          />
          <Label htmlFor={`checkbox-${field.name}-${opt.value}`} className="font-normal">
            {opt.label}
          </Label>
        </div>
      );
    })}
  </div>
);

export default CheckboxRenderer;

// packages/vue/src/components/CheckboxRenderer.vue
<script setup lang="ts">
import type { FieldRendererProps } from '../fieldComponentMap';
import Checkbox from '../components/Checkbox.vue';
import Label from '../components/Label.vue';

const props = defineProps<FieldRendererProps>();
const emit = defineEmits<{ 'update:modelValue': [value: any] }>();

const handleChange = (optValue: any, checked: boolean) => {
  const current = Array.isArray(props.modelValue) ? [...props.modelValue] : [];
  if (checked) {
    current.push(optValue);
  } else {
    const idx = current.indexOf(optValue);
    if (idx > -1) current.splice(idx, 1);
  }
  emit('update:modelValue', current);
};
</script>

<template>
  <div class="flex flex-wrap gap-4">
    <div v-for="opt in field.options" :key="opt.value" class="flex items-center space-x-2">
      <Checkbox
        :id="`checkbox-${field.name}-${opt.value}`"
        :disabled="typeof field.disabled === 'boolean' ? field.disabled : undefined"
        :checked="Array.isArray(modelValue) && modelValue.includes(opt.value)"
        @update:checked="(checked) => handleChange(opt.value, !!checked)"
      />
      <Label :for="`checkbox-${field.name}-${opt.value}`" class="font-normal">
        {{ opt.label }}
      </Label>
    </div>
  </div>
</template>
