// packages/react/src/components/SwitchRenderer.tsx
import React from 'react';
import type { FieldRenderContext } from './types';
import { Switch } from './Switch';

const SwitchRenderer: React.FC<FieldRenderContext> = ({
  field,
  value,
  onChange,
  onBlur,
  fieldId,
  ariaInvalid,
  ariaRequired,
  ariaDescribedBy,
}) => {
  return (
    <div className="flex items-center space-x-2">
      <Switch
        id={fieldId}
        checked={!!value}
        onCheckedChange={onChange}
        disabled={typeof field.disabled === 'boolean' ? field.disabled : undefined}
        name={field.name}
        aria-invalid={ariaInvalid}
        aria-required={ariaRequired}
        aria-describedby={ariaDescribedBy}
      />
    </div>
  );
};

export default SwitchRenderer;

// packages/vue/src/components/SwitchRenderer.vue
<script setup lang="ts">
import type { FormField } from 'pdyform-core';
import Switch from './Switch.vue';

defineProps<{
  field: FormField;
  modelValue: boolean;
  fieldId: string;
  ariaInvalid?: boolean;
  ariaRequired?: boolean;
  ariaDescribedby?: string;
}>();

const emit = defineEmits(['update:modelValue', 'blur']);
</script>

<template>
  <div class="flex items-center space-x-2">
    <Switch
      :id="fieldId"
      :checked="modelValue"
      :disabled="typeof field.disabled === 'boolean' ? field.disabled : undefined"
      :aria-invalid="ariaInvalid"
      :aria-required="ariaRequired"
      :aria-describedby="ariaDescribedby"
      @update:checked="(val) => emit('update:modelValue', val)"
    />
  </div>
</template>
